'use client';
import { reportsData } from '@/constants/mockData';
import styles from '../guarantors/page.module.scss';
import { FaChartBar, FaDownload, FaCheckCircle, FaClock } from 'react-icons/fa';

export default function ReportsPage() {
  return (
    <section className={styles.page}>
      <div className={styles.header}>
        <h1>Reports</h1>
        <p>Generate and download business reports and analytics</p>
      </div>

      <div className={styles.stats}>
        <div className={styles.statCard}>
          <FaChartBar className={styles.icon} />
          <div>
            <p className={styles.value}>{reportsData.length}</p>
            <p className={styles.label}>Total Reports</p>
          </div>
        </div>
        <div className={styles.statCard}>
          <FaCheckCircle className={styles.icon} style={{ color: '#00C9A7' }} />
          <div>
            <p className={styles.value}>{reportsData.filter(r => r.status === 'Available').length}</p>
            <p className={styles.label}>Available</p>
          </div>
        </div>
      </div>

      <div className={styles.tableContainer}>
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Title</th>
              <th>Type</th>
              <th>Generated By</th>
              <th>Date</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {reportsData.map((report) => (
              <tr key={report.id}>
                <td>{report.title}</td>
                <td>{report.type}</td>
                <td>{report.generatedBy}</td>
                <td>{report.date}</td>
                <td>
                  <span className={`${styles.status} ${
                    report.status === 'Available' ? styles.active : ''
                  }`}>
                    {report.status === 'Available' ? <FaCheckCircle /> : <FaClock />}
                    {report.status}
                  </span>
                </td>
                <td>
                  {report.status === 'Available' && (
                    <button style={{
                      background: '#39CDCC',
                      color: '#fff',
                      border: 'none',
                      padding: '0.5rem 1rem',
                      borderRadius: '6px',
                      cursor: 'pointer',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '0.5rem'
                    }}>
                      <FaDownload /> Download
                    </button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}
